# 上下文初始化加载
info:
  name: eureka

server:
  port: 8761

# 配置eureka
eureka:
  instance:
    ######################### 续约 心跳 下线 #########################
    # 心跳，租约续约频率，单位：秒
    lease-renewal-interval-in-seconds: 30
    # eureka server多久没有收到心跳，则表示对应的实例过期，单位：秒
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
