# 上下文初始化加载
info:
  name: lesson-3-feign

server:
  port: 8080

# 配置eureka，作为eureka客户端，既向eureka服务端注册服务，又向eureka服务端获取服务
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

# 开启熔断机制，不然不会生效fallback = FeignSmsMvcClientFailback.class
feign:
  hystrix:
    enabled: true        # true使用熔断机制；false不适用熔断机制
    


  
  